// Package broker wraps an embedded MQTT broker (mochi-mqtt) for the border nodes.
//
// The rules, from reading firmware MQTT.cpp (see the vault note "InterMesh Firmware
// Findings"): a gateway connects with its node ID as the client ID, publishes uplink
// to ROOT/2/e/CHANNEL/GATEWAYID and subscribes to ROOT/2/e/CHANNEL/+ for each channel
// with downlink on, plus ROOT/2/e/PKI/+. The broker enforces a per-gateway credential
// limited to named channels, and never delivers one gateway's uplink to another gateway:
// the server alone decides what is downlinked, according to each channel's scope.
//
// Isolation works through the per-delivery read check: the broker asks OnACLCheck whether
// a client may read each concrete topic before delivering to it. A gateway may be delivered
// only topics whose last segment is the server's own node id (for all gateways) or that id
// followed by "." and the gateway's own id (for one gateway). An uplink from another gateway
// ends in that gateway's id, so it is never delivered. (mochi's OnSelectSubscribers hook runs
// only for shared subscriptions, so it cannot do this.)
package broker

import (
	"bytes"
	"crypto/sha256"
	"crypto/subtle"
	"crypto/tls"
	"fmt"
	"log/slog"
	"strings"

	mqtt "github.com/mochi-mqtt/server/v2"
	"github.com/mochi-mqtt/server/v2/listeners"
	"github.com/mochi-mqtt/server/v2/packets"

	"github.com/Poag/Intermesh/server/internal/state"
)

// PKIChannel is the channel ID gateways use for PKI direct messages.
const PKIChannel = "PKI"

// MaxPayload is the largest publish accepted. A ServiceEnvelope is at most a few hundred
// bytes (the firmware client buffer is 1024).
const MaxPayload = 2048

// Uplink is one packet published by a gateway.
type Uplink struct {
	Username  string // the gateway's credential
	GatewayID string // the gateway's node id as written in the topic ("!a1b2c3d4")
	Channel   string // channel name from the topic, or "PKI"
	Payload   []byte // a ServiceEnvelope protobuf
}

// Broker is the embedded MQTT broker.
type Broker struct {
	srv      *mqtt.Server
	st       *state.State
	root     string
	serverID string
	uplink   func(Uplink)
	log      *slog.Logger
}

// New creates a broker for topics under root (the gateways' configured root, "msh" by
// default). uplink receives every accepted publish.
func New(st *state.State, root, serverID string, uplink func(Uplink), log *slog.Logger) (*Broker, error) {
	if !validGatewayID(serverID) {
		return nil, fmt.Errorf("broker: server id %q is not a node id", serverID)
	}
	if log == nil {
		log = slog.Default()
	}
	root = strings.Trim(root, "/")
	if root == "" {
		root = "msh"
	}
	caps := mqtt.NewDefaultServerCapabilities()
	caps.MaximumPacketSize = 4096
	caps.RetainAvailable = 0
	caps.MaximumClients = 256
	srv := mqtt.New(&mqtt.Options{InlineClient: true, Capabilities: caps, Logger: log})
	b := &Broker{srv: srv, st: st, root: root, serverID: serverID, uplink: uplink, log: log}
	if err := srv.AddHook(&hook{b: b}, nil); err != nil {
		return nil, err
	}
	return b, nil
}

// Listen adds a TCP listener, with TLS when tlsCfg is not nil (the MQTT listener must use
// TLS once exposed to the internet).
func (b *Broker) Listen(addr string, tlsCfg *tls.Config) error {
	return b.srv.AddListener(listeners.NewTCP(listeners.Config{Type: listeners.TypeTCP, ID: "gateways-" + addr, Address: addr, TLSConfig: tlsCfg}))
}

// Serve starts the listeners.
func (b *Broker) Serve() error { return b.srv.Serve() }

// Close stops the broker.
func (b *Broker) Close() error { return b.srv.Close() }

// DownlinkTopic returns the topic a downlink is published on: to every gateway subscribed to
// the channel when target is empty, or to one gateway when it names that gateway's node id.
func (b *Broker) DownlinkTopic(channel, target string) string {
	last := b.serverID
	if target != "" {
		last += "." + target
	}
	return b.root + "/2/e/" + channel + "/" + last
}

// Publish sends a downlink packet. channel is the channel name as the gateway has it
// configured, or "PKI" for a direct message. An empty target means every gateway
// subscribed to the channel.
func (b *Broker) Publish(channel, target string, payload []byte) error {
	return b.srv.Publish(b.DownlinkTopic(channel, target), payload, false, 0)
}

// HashPassword is how gateway passwords are stored: SHA-256 of salt and password. The
// passwords are random 128-bit values generated by the server, so a slow hash is not needed.
func HashPassword(salt []byte, password string) []byte {
	h := sha256.New()
	h.Write(salt)
	h.Write([]byte(password))
	return h.Sum(nil)
}

// parseUplinkTopic splits ROOT/2/e/CHANNEL/GATEWAYID.
func (b *Broker) parseUplinkTopic(topic string) (channel, gateway string, ok bool) {
	prefix := b.root + "/2/e/"
	if !strings.HasPrefix(topic, prefix) {
		return "", "", false
	}
	rest := strings.TrimPrefix(topic, prefix)
	i := strings.LastIndex(rest, "/")
	if i <= 0 || i == len(rest)-1 {
		return "", "", false
	}
	return rest[:i], rest[i+1:], true
}

func allowedChannel(g *state.Gateway, channel string) bool {
	if channel == PKIChannel {
		return true
	}
	for _, c := range g.Channels {
		if strings.EqualFold(c, channel) {
			return true
		}
	}
	return false
}

func validGatewayID(id string) bool {
	if len(id) != 9 || id[0] != '!' {
		return false
	}
	for _, c := range id[1:] {
		if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f') {
			return false
		}
	}
	return true
}

type hook struct {
	mqtt.HookBase
	b *Broker
}

func (h *hook) ID() string { return "intermesh-gateways" }

func (h *hook) Provides(b byte) bool {
	return bytes.Contains([]byte{mqtt.OnConnectAuthenticate, mqtt.OnACLCheck, mqtt.OnPublish, mqtt.OnPublished}, []byte{b})
}

func (h *hook) gateway(cl *mqtt.Client) (*state.Gateway, bool) {
	if cl == nil {
		return nil, false
	}
	return h.b.st.Gateway(string(cl.Properties.Username))
}

func (h *hook) OnConnectAuthenticate(cl *mqtt.Client, pk packets.Packet) bool {
	user := string(pk.Connect.Username)
	g, ok := h.b.st.Gateway(user)
	if !ok {
		h.b.log.Info("mqtt: unknown gateway user", "user", user, "remote", cl.Net.Remote)
		return false
	}
	if subtle.ConstantTimeCompare(HashPassword(g.Salt, string(pk.Connect.Password)), g.PassHash) != 1 {
		h.b.log.Info("mqtt: wrong password", "user", user, "remote", cl.Net.Remote)
		return false
	}
	if !validGatewayID(cl.ID) {
		h.b.log.Info("mqtt: client id is not a node id", "user", user, "client", cl.ID)
		return false
	}
	h.b.st.NoteGatewayNode(user, cl.ID)
	return true
}

func (h *hook) OnACLCheck(cl *mqtt.Client, topic string, write bool) bool {
	if cl != nil && cl.Net.Inline {
		return true
	}
	g, ok := h.gateway(cl)
	if !ok {
		return false
	}
	if write {
		channel, gw, ok := h.b.parseUplinkTopic(topic)
		// The gateway id in the topic must be the connected client's own id.
		return ok && gw == cl.ID && allowedChannel(g, channel)
	}
	// Reads are checked twice by the broker: for a subscription filter (the firmware sends
	// ROOT/2/e/CHANNEL/+) and again for each concrete topic delivered to the client.
	channel, last, ok := h.b.parseUplinkTopic(topic)
	if !ok || !allowedChannel(g, channel) {
		return false
	}
	return last == "+" || last == h.b.serverID || last == h.b.serverID+"."+cl.ID
}

func (h *hook) OnPublish(cl *mqtt.Client, pk packets.Packet) (packets.Packet, error) {
	if cl != nil && cl.Net.Inline {
		return pk, nil
	}
	if len(pk.Payload) > MaxPayload {
		return pk, packets.ErrRejectPacket
	}
	pk.FixedHeader.Retain = false
	return pk, nil
}

func (h *hook) OnPublished(cl *mqtt.Client, pk packets.Packet) {
	if cl == nil || cl.Net.Inline || h.b.uplink == nil {
		return
	}
	channel, gw, ok := h.b.parseUplinkTopic(pk.TopicName)
	if !ok || gw != cl.ID {
		return
	}
	h.b.uplink(Uplink{Username: string(cl.Properties.Username), GatewayID: gw, Channel: channel, Payload: append([]byte(nil), pk.Payload...)})
}
